#Requires AutoHotkey v2.0
#SingleInstance Force
WinActivate("Roblox")

Send ("{s down}")
Sleep(1300)
Send ("{s up}")
Sleep(100)
Send ("{d down}")
Sleep(500)
Send ("{d up}")
Sleep(100)
Send ("{s down}")
Sleep(900)
Send ("{s up}")
Sleep(100)
Send ("{a down}")
Sleep(800)
Send ("{a up}")
Sleep(100)
Send ("{w down}")
Send ("{Space down}")
Sleep(200)
Send ("{Space up}")
Sleep(500)
Send ("{Space down}")
Sleep(200)
Send ("{Space up}")
Sleep(1000)
Send ("{Space down}")
Sleep(200)
Send ("{Space up}")
Sleep(1700)
Send ("{w up}")
Sleep(100)
Send ("{a down}")
Sleep(600)
Send ("{a up}")
loop 3
{
    Send ("{e}")
    Sleep(50)
}
Sleep(100)
Send ("{w down}")
Sleep(4200)
Send ("{w up}")
Sleep(100)
Send ("{a down}")
Sleep(1300)
Send ("{a up}")
loop 3
    {
        Send ("{e}")
        Sleep(50)
    }
Send ("{d down}")
Sleep(1600)
Send ("{d up}")
Sleep(200)
Send ("{w down}")
Sleep(800)
Send ("{w up}")
loop 3
    {
        Send ("{e}")
        Sleep(50)
    }
    Send ("{s down}")
    Sleep(400)
    Send ("{Space down}")
    Sleep(200)
    Send ("{Space up}")
    Sleep(200)
    Send ("{s up}")
    Send ("{d down}")
    Sleep(1400)
    Send ("{d up}")
    Send ("{s down}")
    Sleep(3000)
    Send ("{s up}")
    Send ("{d down}")
    Sleep(1500)
    Send ("{d up}")
    Sleep(300)
    Send ("{s down}")
    Sleep(400)
    Send ("{s up}")
    loop 3
        {
            Send ("{e}")
            Sleep(50)
        }
    Send ("{w down}")
    Sleep(200)
    Send ("{space down}")
    Sleep(400)
    Send ("{space up}")
    Send ("{w up}")
    Sleep(100)
    Send ("{d down}")
    Sleep(1800)
    Send ("{d up}")
    Sleep(100)
    Send ("{w down}")
    Sleep(500)
    Send ("{w up}")
    loop 3
        {
            Send ("{e}")
            Sleep(50)
        }
    loop 3
        {
            Send ("{e}")
            Sleep(50)
        }
        sleep(300)
    Send ("{space down}")
    Send ("{a down}")
    Sleep(500)
    Send ("{a up}")
    Send ("{w down}")
    Sleep(700)
    Send ("{space up}")
    Sleep(1400)
    Send ("{w up}")
    Send ("{d down}")
    Sleep(1800)
    Send ("{d up}")
    loop 3
        {
            Send ("{e}")
            Sleep(50)
        }
Send ("{d down}")
Sleep(700)
Send ("{d up}")
Send ("{s down}")
Sleep(4700)
Send ("{s up}")
Send ("{d down}")
Sleep(3500)
Send ("{d up}")
loop 3
    {
        Send ("{e}")
        Sleep(50)
    }
Send ("{s down}")
Sleep(500)
Send ("{s up}")
Send ("{d down}")
Sleep(1300)
Send ("{space down}")
Sleep(100)
Send ("{space up}")
Sleep(2200)
Send ("{d up}")
Send ("{w down}")
Sleep(4700)
Send ("{w up}")
loop 3
    {
        Send ("{e}")
        Sleep(50)
    }
Send ("{s down}")
Sleep(2000)
Send ("{space down}")
Sleep(1000)
Send ("{space up}")
Sleep(2300)
Send ("{space down}")
Sleep(500)
Send ("{s up}")
Send ("{space up}")
Sleep(300)
Send ("{d down}")
Sleep(1300)
Send ("{d up}")
loop 3
    {
        Send ("{e}")
        Sleep(50)
    }
    Send ("{a down}")
    Sleep(1300)
    Send ("{a up}")
    Sleep(500)
    Send ("{s down}")
    Sleep(2900)
    Send ("{s up}")
    Send ("{a down}")
    Sleep(400)
    Send ("{a up}")
    loop 3
        {
            Send ("{e}")
            Sleep(50)
        }
Send ("{s down}")
Sleep(2500)
Send ("{s up}")
Send ("{a down}")
Sleep(1500)
Send ("{a up}")
Send ("{s down}")
Send ("{space down}")
Sleep(600)
Send ("{s up}")
Send ("{space up}")
Send ("{a down}")
Sleep(2700)
Send ("{a up}")
Send ("{s down}")
Sleep(4000)
Send ("{s up}")
Send ("{a down}")
Sleep(2000)
Send ("{a up}")

Run('C:\Program Files\AutoHotkey\v2\AutoHotkey64.exe "' A_ScriptDir '\AutoEquip.ahk"')